### PR TITLE
Update Prod Bundle files

### PR DESCRIPTION
**Pull request by chenyixuan625**
These new Bundle files gather all the active customers who have been onboarded to FHIR(both Millennium and Soarian Clinical), get each of the organization name, address, identifier(s), the URL along with other fields that are based on the FHIR Endpoint and FHIR Organization specifications.

The logic to get identifier(s): we use FHIR Organization API to retrieve the customer's identifiers first. Use OID if there is a valid OID, if there is no OID, use TAX ID, and if there is no TAX ID, use Organization NPI. And if there is no Organization NPI, use all practitioners' NPIs for the tenant/organization.

### CODE REVIEW

**Review by kolkheang — DISMISSED** [review]

**Comment by timharsch** [comment]
For those of us who don't have access to Cerner's private Jira instance it would be nice if a little color could be added to the description.  What's the motivation for the new update, what has changed?    I notice a large number of addresses are missing in this update, which will likely have a downstream effect on consumers.  our app was able to use address info for locality searches.

**Comment by kolkheang** [comment]
Hello @timharsch , this PR contains the updated FHIR endpoints based on the new ONC HTI-1 requirements.

Could you please share the listing of addresses that are missing? Please also include the FHIR URL as well.

**Comment by timharsch** [comment]
Thanks for the reply.  When comparing diffs it looked like the addresses were removed, but looking at the new file I see it has just moved to Organization.   That makes sense. 👍 

Any plans to include sysadmin contact info (https://hl7.org/fhir/r4/endpoint-definitions.html#Endpoint.contact)? Our app encounters servers that go down for months sometimes, or API calls that return HTTP 500s on a regular basis.

**Review by jfrhong — APPROVED** [review]

**Comment by jfrhong** [comment]
@timharsch, we currently don't have plans to include a contact. However, if you are having difficulties with the FHIR APIs, you can reach out to us at https://forums.oracle.com/ords/apexds/domain/open-developer-experience for help troubleshooting.

**Pull request merged**
